import { HttpResponse, http } from 'msw'
import type {
  DietQualityAssessment,
  DietQualityGoal,
  DietQualityGoalProgress,
  DietQualityInstrument,
  DietQualityQuestion,
  DietQualitySummary,
} from '@/api/generated/model'

const ALCOHOL_NOTICE =
  'Este instrumento histórico incluye una pregunta sobre vino. La aplicación no recomienda comenzar ni aumentar el consumo de alcohol para modificar el puntaje.'

const numberQuestion = (code: string, order: number, prompt: string, overrides: Partial<DietQualityQuestion> = {}): DietQualityQuestion => ({
  code,
  order,
  prompt,
  helper_text: null,
  answer_type: 'number',
  unit: 'servings_per_day',
  max_value: 100,
  direction: 'at_least',
  period: 'day',
  actionable: true,
  goal_available: true,
  safety_excluded: false,
  exclusion_reason: null,
  ...overrides,
})

export const instrumentFixture: DietQualityInstrument = {
  code: 'medas_14',
  version: '1.0.0',
  locale: 'es-MX',
  name: 'MEDAS-14',
  description: 'Screener de patrón mediterráneo.',
  max_score: 14,
  evidence_reviewed_at: '2026-07-05',
  checksum: 'a'.repeat(64),
  source: { primary: { citation: 'Martínez-González et al. 2012' } },
  limitations: ['Es un screener autodeclarado.'],
  safety_notices: [ALCOHOL_NOTICE],
  questions: [
    {
      code: 'olive_oil_main_fat',
      order: 1,
      prompt: '¿Usas aceite de oliva como la principal grasa para cocinar o aderezar?',
      helper_text: null,
      answer_type: 'boolean',
      unit: null,
      max_value: null,
      direction: 'binary',
      period: 'day',
      actionable: true,
      goal_available: true,
      safety_excluded: false,
      exclusion_reason: null,
    },
    numberQuestion('olive_oil_tbsp_day', 2, '¿Cuántas cucharadas de aceite de oliva consumes en total al día?', {
      unit: 'tablespoons_per_day',
      actionable: false,
      goal_available: false,
    }),
    numberQuestion('vegetable_servings_day', 3, '¿Cuántas porciones de verduras y hortalizas consumes al día?', {
      helper_text: 'Una porción principal equivale aproximadamente a 200 g.',
    }),
    numberQuestion('fruit_units_day', 4, '¿Cuántas piezas de fruta consumes al día?', { unit: 'units_per_day' }),
    numberQuestion('red_processed_meat_servings_day', 5, '¿Cuántas porciones de carne roja o procesada consumes al día?', {
      direction: 'at_most',
    }),
    numberQuestion('butter_margarine_cream_servings_day', 6, '¿Cuántas porciones de mantequilla, margarina o crema consumes al día?', {
      direction: 'at_most',
    }),
    numberQuestion('sweetened_beverages_day', 7, '¿Cuántas bebidas azucaradas consumes al día?', { direction: 'at_most' }),
    numberQuestion('wine_glasses_week', 8, '¿Cuántas copas de vino consumes por semana?', {
      unit: 'glasses_per_week',
      max_value: 700,
      period: 'week',
      actionable: false,
      goal_available: false,
      safety_excluded: true,
      exclusion_reason: 'alcohol_safety',
      helper_text: ALCOHOL_NOTICE,
    }),
    numberQuestion('legume_servings_week', 9, '¿Cuántas porciones de leguminosas consumes por semana?', {
      unit: 'servings_per_week',
      max_value: 700,
      period: 'week',
    }),
    numberQuestion('fish_seafood_servings_week', 10, '¿Cuántas porciones de pescado o mariscos consumes por semana?', {
      unit: 'servings_per_week',
      max_value: 700,
      period: 'week',
    }),
    numberQuestion('commercial_pastries_week', 11, '¿Cuántas veces por semana consumes repostería comercial?', {
      unit: 'servings_per_week',
      max_value: 700,
      period: 'week',
      direction: 'at_most',
    }),
    numberQuestion('nuts_servings_week', 12, '¿Cuántas porciones de nueces consumes por semana?', {
      unit: 'servings_per_week',
      max_value: 700,
      period: 'week',
    }),
    {
      code: 'prefer_white_meat',
      order: 13,
      prompt: '¿Sueles preferir pollo, pavo o alternativas equivalentes frente a carne de res, cerdo, hamburguesas o embutidos?',
      helper_text: null,
      answer_type: 'boolean',
      unit: null,
      max_value: null,
      direction: 'binary',
      period: 'day',
      actionable: true,
      goal_available: true,
      safety_excluded: false,
      exclusion_reason: null,
    },
    numberQuestion('sofrito_servings_week', 14, '¿Cuántas veces por semana consumes sofrito?', {
      unit: 'servings_per_week',
      max_value: 700,
      period: 'week',
    }),
  ],
}

export const assessmentFixture: DietQualityAssessment = {
  id: 42,
  instrument_code: 'medas_14',
  instrument_version: '1.0.0',
  instrument_locale: 'es-MX',
  score: 9,
  max_score: 14,
  completed_local_date: '2026-06-23',
  completed_at: '2026-06-23T20:00:00Z',
  evidence_reviewed_at: '2026-07-05',
  items: instrumentFixture.questions.map((q) => ({
    question_code: q.code,
    question_order: q.order,
    prompt: q.prompt,
    helper_text: q.helper_text,
    answer: q.answer_type === 'boolean' ? true : 1,
    unit: q.unit,
    points: ['legume_servings_week', 'vegetable_servings_day', 'wine_glasses_week', 'fruit_units_day', 'nuts_servings_week'].includes(q.code) ? 0 : 1,
    met: !['legume_servings_week', 'vegetable_servings_day', 'wine_glasses_week', 'fruit_units_day', 'nuts_servings_week'].includes(q.code),
    actionable: q.actionable,
    goal_available: q.goal_available,
    safety_excluded: q.safety_excluded,
    exclusion_reason: q.exclusion_reason,
  })),
  unmet_actionable_codes: ['legume_servings_week', 'vegetable_servings_day', 'fruit_units_day', 'nuts_servings_week'],
  safety_notices: [ALCOHOL_NOTICE],
  limitations: ['Es un screener autodeclarado.'],
  source: { primary: { citation: 'Martínez-González et al. 2012' } },
}

export const goalFixture: DietQualityGoal = {
  id: 7,
  user_id: 1,
  source_assessment_id: 42,
  focus_code: 'legume_servings_week',
  title: 'Porciones de leguminosas por semana',
  description: 'Registra tu consumo; el componente del instrumento corresponde a al menos 3 porciones por semana.',
  direction: 'at_least',
  period: 'week',
  target_value: 3,
  unit: 'servings_per_week',
  starts_on: '2026-06-24',
  ends_on: null,
  status: 'active',
  source_instrument_code: 'medas_14',
  source_instrument_version: '1.0.0',
  disclaimer: 'Estas metas son opcionales y las eliges tú.',
}

export const goalProgressFixture: DietQualityGoalProgress = {
  goal_id: 7,
  direction: 'at_least',
  period: 'week',
  period_start: '2026-06-22',
  period_end: '2026-06-28',
  recorded_value: 1,
  target_value: 3,
  remaining_value: 2,
  remaining_allowance: null,
  comparison: 'below_threshold_so_far',
  data_points: 1,
  expected_data_points: 3,
  coverage_pct: 33.3,
  is_period_complete: false,
}

export const summaryFixture: DietQualitySummary = {
  period_days: 90,
  latest_assessment: {
    id: 42,
    instrument_code: 'medas_14',
    instrument_version: '1.0.0',
    instrument_locale: 'es-MX',
    score: 9,
    max_score: 14,
    completed_local_date: '2026-06-23',
    completed_at: '2026-06-23T20:00:00Z',
  },
  previous_assessment: {
    id: 40,
    instrument_code: 'medas_14',
    instrument_version: '1.0.0',
    instrument_locale: 'es-MX',
    score: 7,
    max_score: 14,
    completed_local_date: '2026-05-20',
    completed_at: '2026-05-20T20:00:00Z',
  },
  score_delta: 2,
  history: [
    { assessment_id: 40, score: 7, max_score: 14, completed_local_date: '2026-05-20' },
    { assessment_id: 42, score: 9, max_score: 14, completed_local_date: '2026-06-23' },
  ],
  component_summary: assessmentFixture.items.map((item) => ({
    question_code: item.question_code,
    question_order: item.question_order,
    prompt: item.prompt,
    met: item.met,
    points: item.points,
    actionable: item.actionable,
    goal_available: item.goal_available,
    safety_excluded: item.safety_excluded,
  })),
  focus_candidates: [
    {
      focus_code: 'legume_servings_week',
      title: 'Porciones de leguminosas por semana',
      description: 'Registra tu consumo; el componente corresponde a al menos 3 porciones por semana.',
      direction: 'at_least',
      period: 'week',
      target_value: 3,
      unit: 'servings_per_week',
      source_question_code: 'legume_servings_week',
      disclaimer: 'Estas metas son opcionales y las eliges tú.',
    },
    {
      focus_code: 'vegetable_servings_day',
      title: 'Porciones de verduras al día',
      description: 'Registra tu consumo; el componente corresponde a al menos 2 porciones al día.',
      direction: 'at_least',
      period: 'day',
      target_value: 2,
      unit: 'servings_per_day',
      source_question_code: 'vegetable_servings_day',
      disclaimer: 'Estas metas son opcionales y las eliges tú.',
    },
  ],
  active_goals: [goalFixture],
  goal_progress: [goalProgressFixture],
  assessment_age_days: 12,
  can_retake: false,
}

export const dietQualityHandlers = [
  http.get('/api/diet-quality/instruments/medas-14', () => HttpResponse.json({ instrument: instrumentFixture })),
  http.get('/api/diet-quality/summary', () => HttpResponse.json(summaryFixture)),
  http.get('/api/diet-quality/assessments/latest', () => HttpResponse.json({ assessment: assessmentFixture })),
  http.get('/api/diet-quality/assessments/:id', () => HttpResponse.json({ assessment: assessmentFixture })),
  http.get('/api/diet-quality/goals', () => HttpResponse.json({ goals: [goalFixture], progress: [goalProgressFixture] })),
  http.post('/api/diet-quality/assessments', () => HttpResponse.json({ assessment: assessmentFixture }, { status: 201 })),
  http.post('/api/diet-quality/goals', () => HttpResponse.json({ goal: goalFixture }, { status: 201 })),
  http.put('/api/diet-quality/goals/:id', () => HttpResponse.json({ goal: { ...goalFixture, status: 'paused' } })),
  http.put('/api/diet-quality/goals/:id/check-ins/:date', () =>
    HttpResponse.json({ check_in: { id: 1, diet_quality_goal_id: 7, local_date: '2026-06-24', value: 1, note: null } }),
  ),
]
