import { HttpResponse, http } from 'msw'
import type {
  DailyNutrientIntakeResponse,
  NutrientDefinition,
  NutrientDetailResponse,
  NutrientReferenceResponse,
  PeriodNutrientIntakeResponse,
} from '@/api/generated/model'

const emptyQualityBreakdown = { verified: 0, source_reported: 0, user_reported: 0, estimated: 0, unknown: 0 }

export const nutrientCatalogFixture: NutrientDefinition[] = [
  { code: 'energy_kcal', name: 'Energía', unit: 'kcal', category: 'energy', display_precision: 0, is_reference_eligible: false, description: null },
  { code: 'protein_g', name: 'Proteína', unit: 'g', category: 'macro', display_precision: 1, is_reference_eligible: false, description: null },
  { code: 'carbohydrate_g', name: 'Carbohidratos', unit: 'g', category: 'macro', display_precision: 1, is_reference_eligible: false, description: null },
  { code: 'fat_g', name: 'Grasas totales', unit: 'g', category: 'macro', display_precision: 1, is_reference_eligible: false, description: null },
  { code: 'fiber_g', name: 'Fibra dietética', unit: 'g', category: 'other', display_precision: 1, is_reference_eligible: true, description: null },
  { code: 'sodium_mg', name: 'Sodio', unit: 'mg', category: 'mineral', display_precision: 0, is_reference_eligible: true, description: null },
  { code: 'calcium_mg', name: 'Calcio', unit: 'mg', category: 'mineral', display_precision: 0, is_reference_eligible: true, description: null },
  { code: 'iron_mg', name: 'Hierro', unit: 'mg', category: 'mineral', display_precision: 1, is_reference_eligible: true, description: null },
  { code: 'magnesium_mg', name: 'Magnesio', unit: 'mg', category: 'mineral', display_precision: 0, is_reference_eligible: true, description: null },
  { code: 'potassium_mg', name: 'Potasio', unit: 'mg', category: 'mineral', display_precision: 0, is_reference_eligible: true, description: null },
  { code: 'zinc_mg', name: 'Zinc', unit: 'mg', category: 'mineral', display_precision: 1, is_reference_eligible: true, description: null },
  { code: 'vitamin_a_rae_mcg', name: 'Vitamina A', unit: 'mcg RAE', category: 'vitamin', display_precision: 0, is_reference_eligible: true, description: null },
  { code: 'vitamin_c_mg', name: 'Vitamina C', unit: 'mg', category: 'vitamin', display_precision: 0, is_reference_eligible: true, description: null },
  { code: 'vitamin_d_mcg', name: 'Vitamina D', unit: 'mcg', category: 'vitamin', display_precision: 1, is_reference_eligible: true, description: null },
  { code: 'vitamin_b12_mcg', name: 'Vitamina B12', unit: 'mcg', category: 'vitamin', display_precision: 1, is_reference_eligible: true, description: null },
  { code: 'folate_dfe_mcg', name: 'Folato', unit: 'mcg DFE', category: 'vitamin', display_precision: 0, is_reference_eligible: true, description: null },
]

export const undisclosedReferencesFixture: NutrientReferenceResponse = {
  reference_set: {
    code: 'nasem_dri_general_adults',
    version: '1.0.0',
    jurisdiction: 'US_CA',
    population_scope: 'apparently_healthy_nonpregnant_nonlactating',
    evidence_reviewed_at: '2026-07-05',
    sources: [],
    limitations: ['Referencias diseñadas para personas sanas de 18 años o más.'],
  },
  context: { date: '2026-07-05', age_years: 25, sex_basis: 'undisclosed' },
  references: [
    {
      nutrient_code: 'iron_mg',
      reference_type: 'RDA',
      reference_mode: 'range',
      value: null,
      minimum: 8,
      maximum: 18,
      unit: 'mg',
      direction: 'at_least',
      is_primary: true,
      sex_basis: 'undisclosed',
      limitations: [],
      source_note: null,
    },
    {
      nutrient_code: 'calcium_mg',
      reference_type: 'RDA',
      reference_mode: 'exact',
      value: 1000,
      minimum: null,
      maximum: null,
      unit: 'mg',
      direction: 'at_least',
      is_primary: true,
      sex_basis: 'all',
      limitations: [],
      source_note: null,
    },
  ],
  reason: null,
}

export const noProfileContextReferencesFixture: NutrientReferenceResponse = {
  reference_set: null,
  context: { date: '2026-07-05', age_years: null, sex_basis: null },
  references: [],
  reason: 'profile_context_unavailable',
}

export const dailyIntakeFixture: DailyNutrientIntakeResponse = {
  date: '2026-07-05',
  timezone: 'America/Mexico_City',
  logged: true,
  items_count: 8,
  context: { date: '2026-07-05', age_years: 25, sex_basis: 'undisclosed' },
  reference_unavailable_reason: null,
  nutrients: [
    {
      code: 'calcium_mg',
      name: 'Calcio',
      unit: 'mg',
      category: 'mineral',
      display_precision: 0,
      value: 650.4,
      status: 'partial',
      coverage: { items_total: 8, items_known: 5, items_unknown: 3, coverage_pct: 62.5 },
      quality_breakdown: { verified: 2, source_reported: 2, user_reported: 1, estimated: 0, unknown: 3 },
      reference: {
        nutrient_code: 'calcium_mg',
        reference_type: 'RDA',
        reference_mode: 'exact',
        value: 1000,
        minimum: null,
        maximum: null,
        unit: 'mg',
        direction: 'at_least',
        is_primary: true,
        sex_basis: 'all',
        limitations: [],
        source_note: null,
      },
      comparison: 'indeterminate',
    },
    {
      code: 'iron_mg',
      name: 'Hierro',
      unit: 'mg',
      category: 'mineral',
      display_precision: 1,
      value: 0,
      status: 'complete',
      coverage: { items_total: 8, items_known: 8, items_unknown: 0, coverage_pct: 100 },
      quality_breakdown: { verified: 8, source_reported: 0, user_reported: 0, estimated: 0, unknown: 0 },
      reference: {
        nutrient_code: 'iron_mg',
        reference_type: 'RDA',
        reference_mode: 'range',
        value: null,
        minimum: 8,
        maximum: 18,
        unit: 'mg',
        direction: 'at_least',
        is_primary: true,
        sex_basis: 'undisclosed',
        limitations: ['La absorción varía según el alimento y el patrón dietético. Este registro no diagnostica anemia.'],
        source_note: null,
      },
      comparison: 'below_reference_range',
    },
    {
      code: 'zinc_mg',
      name: 'Zinc',
      unit: 'mg',
      category: 'mineral',
      display_precision: 1,
      value: null,
      status: 'unknown',
      coverage: { items_total: 8, items_known: 0, items_unknown: 8, coverage_pct: 0 },
      quality_breakdown: emptyQualityBreakdown,
      reference: null,
      comparison: 'indeterminate',
    },
  ],
  limitations: [
    'Los cálculos incluyen los alimentos registrados en la aplicación. No incluyen suplementos, exposición solar, agua ni sal agregada, salvo que esos valores estén incluidos expresamente en el alimento registrado.',
  ],
}

export const periodIntakeFixture: PeriodNutrientIntakeResponse = {
  summary: {
    start_date: '2026-06-06',
    end_date: '2026-07-05',
    timezone: 'America/Mexico_City',
    days_total: 30,
    days_logged: 20,
    diary_coverage_pct: 66.7,
    average_label: 'Promedio de días registrados',
  },
  nutrients: [
    {
      code: 'calcium_mg',
      name: 'Calcio',
      unit: 'mg',
      category: 'mineral',
      display_precision: 0,
      average_value: 620,
      average_label: 'Promedio de días registrados',
      status: 'partial',
      comparison: 'indeterminate',
      reference: {
        nutrient_code: 'calcium_mg',
        reference_type: 'RDA',
        reference_mode: 'exact',
        value: 1000,
        minimum: null,
        maximum: null,
        unit: 'mg',
        direction: 'at_least',
        is_primary: true,
        sex_basis: 'all',
        limitations: [],
        source_note: null,
      },
      informational_references: [],
      reference_changed: false,
      reference_segments: [],
      coverage: {
        days_total: 30,
        days_logged: 20,
        days_with_known_value: 14,
        days_with_partial_value: 4,
        days_with_unknown_value: 2,
        diary_coverage_pct: 66.7,
        nutrient_data_coverage_pct: 68,
      },
      quality_breakdown: { verified: 10, source_reported: 4, user_reported: 0, estimated: 0, unknown: 2 },
    },
    {
      code: 'sodium_mg',
      name: 'Sodio',
      unit: 'mg',
      category: 'mineral',
      display_precision: 0,
      average_value: 2500,
      average_label: 'Promedio de días registrados',
      status: 'complete',
      comparison: 'above_cdrr',
      reference: {
        nutrient_code: 'sodium_mg',
        reference_type: 'CDRR',
        reference_mode: 'exact',
        value: 2300,
        minimum: null,
        maximum: null,
        unit: 'mg',
        direction: 'reduce_if_above',
        is_primary: true,
        sex_basis: 'all',
        limitations: ['La CDRR no es un límite de toxicidad.'],
        source_note: null,
      },
      informational_references: [
        {
          nutrient_code: 'sodium_mg',
          reference_type: 'AI',
          reference_mode: 'exact',
          value: 1500,
          minimum: null,
          maximum: null,
          unit: 'mg',
          direction: 'informational',
          is_primary: false,
          sex_basis: 'all',
          limitations: [],
          source_note: null,
        },
      ],
      reference_changed: false,
      reference_segments: [],
      coverage: {
        days_total: 30,
        days_logged: 20,
        days_with_known_value: 20,
        days_with_partial_value: 0,
        days_with_unknown_value: 0,
        diary_coverage_pct: 66.7,
        nutrient_data_coverage_pct: 100,
      },
      quality_breakdown: { verified: 20, source_reported: 0, user_reported: 0, estimated: 0, unknown: 0 },
    },
    {
      code: 'vitamin_b12_mcg',
      name: 'Vitamina B12',
      unit: 'mcg',
      category: 'vitamin',
      display_precision: 1,
      average_value: null,
      average_label: 'Promedio de días registrados',
      status: 'no_data',
      comparison: 'indeterminate',
      reference: null,
      informational_references: [],
      reference_changed: false,
      reference_segments: [],
      coverage: {
        days_total: 30,
        days_logged: 20,
        days_with_known_value: 0,
        days_with_partial_value: 0,
        days_with_unknown_value: 0,
        diary_coverage_pct: 66.7,
        nutrient_data_coverage_pct: 0,
      },
      quality_breakdown: emptyQualityBreakdown,
    },
  ],
  days: [
    { date: '2026-07-04', logged: true, items_count: 6 },
    { date: '2026-07-05', logged: true, items_count: 8 },
  ],
  reference_segments: [],
  limitations: [
    'Los cálculos incluyen los alimentos registrados en la aplicación. No incluyen suplementos, exposición solar, agua ni sal agregada, salvo que esos valores estén incluidos expresamente en el alimento registrado.',
  ],
}

export const nutrientDetailFixture: NutrientDetailResponse = {
  definition: {
    code: 'sodium_mg',
    name: 'Sodio',
    unit: 'mg',
    category: 'mineral',
    display_precision: 0,
    is_reference_eligible: true,
    description: 'Electrolito presente en muchos alimentos procesados.',
  },
  summary: {
    start_date: '2026-06-06',
    end_date: '2026-07-05',
    timezone: 'America/Mexico_City',
    average_value: 2500,
    average_label: 'Promedio de días registrados',
    status: 'complete',
    comparison: 'above_cdrr',
  },
  reference: {
    nutrient_code: 'sodium_mg',
    reference_type: 'CDRR',
    reference_mode: 'exact',
    value: 2300,
    minimum: null,
    maximum: null,
    unit: 'mg',
    direction: 'reduce_if_above',
    is_primary: true,
    sex_basis: 'all',
    limitations: ['La CDRR no es un límite de toxicidad.'],
    source_note: null,
  },
  informational_references: [
    {
      nutrient_code: 'sodium_mg',
      reference_type: 'AI',
      reference_mode: 'exact',
      value: 1500,
      minimum: null,
      maximum: null,
      unit: 'mg',
      direction: 'informational',
      is_primary: false,
      sex_basis: 'all',
      limitations: [],
      source_note: null,
    },
  ],
  reference_changed: false,
  reference_segments: [],
  coverage: {
    days_total: 30,
    days_logged: 20,
    days_with_known_value: 20,
    days_with_partial_value: 0,
    days_with_unknown_value: 0,
    diary_coverage_pct: 66.7,
    nutrient_data_coverage_pct: 100,
  },
  quality_breakdown: { verified: 20, source_reported: 0, user_reported: 0, estimated: 0, unknown: 0 },
  daily_points: [
    { date: '2026-07-01', value: 2200, status: 'complete' },
    { date: '2026-07-02', value: null, status: 'no_data' },
    { date: '2026-07-03', value: 1800, status: 'partial' },
    { date: '2026-07-04', value: 2600, status: 'complete' },
    { date: '2026-07-05', value: 2500, status: 'complete' },
  ],
  limitations: [
    'La estimación puede omitir sal agregada al cocinar o en la mesa.',
    'La CDRR no es un límite de toxicidad.',
    'Los cálculos incluyen los alimentos registrados en la aplicación. No incluyen suplementos, exposición solar, agua ni sal agregada, salvo que esos valores estén incluidos expresamente en el alimento registrado.',
  ],
}

export const nutrientsHandlers = [
  http.get('/api/nutrients', () => HttpResponse.json({ data: nutrientCatalogFixture })),
  http.get('/api/nutrition/references', () => HttpResponse.json(undisclosedReferencesFixture)),
  http.get('/api/nutrition/intake/daily', () => HttpResponse.json(dailyIntakeFixture)),
  http.get('/api/nutrition/intake/period', () => HttpResponse.json(periodIntakeFixture)),
  http.get('/api/nutrition/intake/nutrients/:code', () => HttpResponse.json(nutrientDetailFixture)),
]
